package com.carlos.artgallery.models.entities;
// Generated 29 mar. 2021 15:44:49 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Art generated by hbm2java
 */
@Entity
@Table(name = "art")
public class Art implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int artid;
	private String title;
	private String description;
	private String author;
	private String url;
	private String tags;
	private Set<User> users = new HashSet<User>();

	public Art() {
	}

	public Art(int artid) {
		this.artid = artid;
	}

	public Art(int artid, String title, String description, String author, String url, String tags, Set<User> users) {
		this.artid = artid;
		this.title = title;
		this.description = description;
		this.author = author;
		this.url = url;
		this.tags = tags;
		this.users = users;
	}

	@Id

	@Column(name = "artid", unique = true, nullable = false)
	public int getArtid() {
		return this.artid;
	}

	public void setArtid(int artid) {
		this.artid = artid;
	}

	@Column(name = "title", length = 100)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "description", length = 10485760)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "author", length = 100)
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	@Column(name = "url", length = 100)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "tags", length = 100)
	public String getTags() {
		return this.tags;
	}

	public void setTags(String tags) {
		this.tags = tags;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "user_art", joinColumns = {
			@JoinColumn(name = "code_art", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "code_user", nullable = false, updatable = false) })
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
