package com.carlos.artgallery.models.entities;
// Generated 29 mar. 2021 15:44:49 by Hibernate Tools 5.2.12.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "usuario")
public class User implements Serializable {

	private static final long serialVersionUID = 1L;
	private int userid;
	private String username;
	private String pass;
	private String description;
	private String pics;
	private String joinDate;
	private Set<Account> accounts = new HashSet<Account>();
	private Set<Art> arts = new HashSet<Art>();

	public User() {
	}

	public User(int userid) {
		this.userid = userid;
	}

	public User(int userid, String username, String pass, String description, String pics, String joinDate,
			Set<Account> accounts, Set<Art> arts) {
		this.userid = userid;
		this.username = username;
		this.pass = pass;
		this.description = description;
		this.pics = pics;
		this.joinDate = joinDate;
		this.accounts = accounts;
		this.arts = arts;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "userid", unique = true, nullable = false)
	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	@Column(name = "username", length = 100)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "pass", length = 100)
	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	@Column(name = "description", length = 10485760)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "pics", length = 100)
	public String getPics() {
		return this.pics;
	}

	public void setPics(String pics) {
		this.pics = pics;
	}

	@Column(name = "join_date", length = 100)
	public String getJoinDate() {
		return this.joinDate;
	}

	public void setJoinDate(String joinDate) {
		this.joinDate = joinDate;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "user_account", joinColumns = {
			@JoinColumn(name = "code_user", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "code_account", nullable = false, updatable = false) })
	public Set<Account> getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Set<Account> accounts) {
		this.accounts = accounts;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "user_art", joinColumns = {
			@JoinColumn(name = "code_user", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "code_art", nullable = false, updatable = false) })
	public Set<Art> getArts() {
		return this.arts;
	}

	public void setArts(Set<Art> arts) {
		this.arts = arts;
	}

}
