package com.carlos.artgallery.models.entities;
// Generated 8 abr. 2021 23:00:46 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario")
public class Usuario implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int userId;
	private String username;
	private String pass;
	private String description;
	private String pics;
	private String joinDate;
	private Set<Art> arts = new HashSet<Art>();
	private Set<Account> accounts = new HashSet<Account>();
	private Set<Comment> comments = new HashSet<Comment>();

	public Usuario() {
	}

	public Usuario(int userId, String joinDate) {
		this.userId = userId;
		this.joinDate = joinDate;
	}

	public Usuario(int userId, String username, String pass, String description, String pics, String joinDate, Set<Art> arts,
			Set<Account> accounts, Set<Comment> comments) {
		this.userId = userId;
		this.username = username;
		this.pass = pass;
		this.description = description;
		this.pics = pics;
		this.joinDate = joinDate;
		this.arts = arts;
		this.accounts = accounts;
		this.comments = comments;
	}

	@Id

	@Column(name = "user_id", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "username", length = 100)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "pass", length = 100)
	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	@Column(name = "description", length = 10485760)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "pics", length = 10485760)
	public String getPics() {
		return this.pics;
	}

	public void setPics(String pics) {
		this.pics = pics;
	}

	@Column(name = "join_date", nullable = false, length = 100)
	public String getJoinDate() {
		return this.joinDate;
	}

	public void setJoinDate(String joinDate) {
		this.joinDate = joinDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Art> getArts() {
		return this.arts;
	}

	public void setArts(Set<Art> arts) {
		this.arts = arts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Account> getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Set<Account> accounts) {
		this.accounts = accounts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Comment> getComments() {
		return this.comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

}
